INSERT INTO books (name, description, cover_url, author_id) VALUES
('Silent River', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-1/640/960', 1),
('Hidden River', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-2/640/960', 2),
('Golden River', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-3/640/960', 3),
('Lost River', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-4/640/960', 4),
('Blue River', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-5/640/960', 5),
('Crimson River', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-6/640/960', 6),
('Ancient River', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-7/640/960', 7),
('Bright River', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-8/640/960', 8),
('Last River', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-9/640/960', 9),
('Fading River', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-10/640/960', 10),
('Northern River', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-11/640/960', 11),
('Southern River', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-12/640/960', 12),
('Emerald River', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-13/640/960', 13),
('Iron River', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-14/640/960', 14),
('Velvet River', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-15/640/960', 15),
('Midnight River', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-16/640/960', 16),
('Broken River', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-17/640/960', 17),
('Wild River', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-18/640/960', 18),
('Secret River', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-19/640/960', 19),
('Lonely River', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-20/640/960', 20),
('Silent City', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-21/640/960', 21),
('Hidden City', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-22/640/960', 22),
('Golden City', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-23/640/960', 23),
('Lost City', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-24/640/960', 24),
('Blue City', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-25/640/960', 25),
('Crimson City', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-26/640/960', 26),
('Ancient City', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-27/640/960', 27),
('Bright City', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-28/640/960', 28),
('Last City', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-29/640/960', 29),
('Fading City', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-30/640/960', 30),
('Northern City', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-31/640/960', 31),
('Southern City', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-32/640/960', 32),
('Emerald City', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-33/640/960', 33),
('Iron City', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-34/640/960', 34),
('Velvet City', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-35/640/960', 35),
('Midnight City', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-36/640/960', 36),
('Broken City', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-37/640/960', 37),
('Wild City', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-38/640/960', 38),
('Secret City', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-39/640/960', 39),
('Lonely City', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-40/640/960', 40),
('Silent Garden', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-41/640/960', 41),
('Hidden Garden', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-42/640/960', 42),
('Golden Garden', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-43/640/960', 43),
('Lost Garden', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-44/640/960', 44),
('Blue Garden', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-45/640/960', 45),
('Crimson Garden', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-46/640/960', 46),
('Ancient Garden', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-47/640/960', 47),
('Bright Garden', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-48/640/960', 48),
('Last Garden', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-49/640/960', 49),
('Fading Garden', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-50/640/960', 50),
('Northern Garden', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-51/640/960', 51),
('Southern Garden', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-52/640/960', 52),
('Emerald Garden', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-53/640/960', 53),
('Iron Garden', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-54/640/960', 54),
('Velvet Garden', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-55/640/960', 55),
('Midnight Garden', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-56/640/960', 56),
('Broken Garden', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-57/640/960', 57),
('Wild Garden', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-58/640/960', 58),
('Secret Garden', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-59/640/960', 59),
('Lonely Garden', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-60/640/960', 60),
('Silent Mountain', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-61/640/960', 61),
('Hidden Mountain', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-62/640/960', 62),
('Golden Mountain', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-63/640/960', 63),
('Lost Mountain', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-64/640/960', 64),
('Blue Mountain', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-65/640/960', 65),
('Crimson Mountain', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-66/640/960', 66),
('Ancient Mountain', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-67/640/960', 67),
('Bright Mountain', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-68/640/960', 68),
('Last Mountain', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-69/640/960', 69),
('Fading Mountain', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-70/640/960', 70),
('Northern Mountain', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-71/640/960', 71),
('Southern Mountain', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-72/640/960', 72),
('Emerald Mountain', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-73/640/960', 73),
('Iron Mountain', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-74/640/960', 74),
('Velvet Mountain', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-75/640/960', 75),
('Midnight Mountain', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-76/640/960', 76),
('Broken Mountain', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-77/640/960', 77),
('Wild Mountain', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-78/640/960', 78),
('Secret Mountain', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-79/640/960', 79),
('Lonely Mountain', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-80/640/960', 80),
('Silent Library', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-81/640/960', 81),
('Hidden Library', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-82/640/960', 82),
('Golden Library', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-83/640/960', 83),
('Lost Library', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-84/640/960', 84),
('Blue Library', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-85/640/960', 85),
('Crimson Library', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-86/640/960', 86),
('Ancient Library', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-87/640/960', 87),
('Bright Library', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-88/640/960', 88),
('Last Library', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-89/640/960', 89),
('Fading Library', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-90/640/960', 90),
('Northern Library', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-91/640/960', 91),
('Southern Library', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-92/640/960', 92),
('Emerald Library', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-93/640/960', 93),
('Iron Library', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-94/640/960', 94),
('Velvet Library', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-95/640/960', 95),
('Midnight Library', 'A heartfelt novel about family, memory, and second chances.', 'https://picsum.photos/seed/book-96/640/960', 96),
('Broken Library', 'A fast-moving story that follows ambition, loyalty, and a difficult choice.', 'https://picsum.photos/seed/book-97/640/960', 97),
('Wild Library', 'An atmospheric tale of friendship, loss, and unexpected hope.', 'https://picsum.photos/seed/book-98/640/960', 98),
('Secret Library', 'A character-driven drama set between old traditions and modern dreams.', 'https://picsum.photos/seed/book-99/640/960', 99),
('Lonely Library', 'A vivid literary journey filled with mystery, resilience, and quiet courage.', 'https://picsum.photos/seed/book-100/640/960', 100);
